//! The window/taskbar icon, embedded in the binary.
//!
//! Setting this at runtime matters because the packaged icon isn't always in
//! play: on macOS a binary run outside an `.app` bundle (`cargo run`) gets the
//! generic "exec" icon in the Dock, and on Linux a window manager that ignores
//! the `.desktop` entry falls back to a default. Compiling the PNG in means the
//! icon is correct however the app was started.
//!
//! `packaging/rworldradio-256.png` is generated by `packaging/make-icons.py`,
//! which also produces the hicolor sizes and the macOS `.icns` from the same
//! drawing.

const ICON_PNG: &[u8] = include_bytes!("../packaging/rworldradio-256.png");

/// Decodes the embedded icon. `None` (with a warning) rather than a panic if it
/// somehow fails - a missing icon is cosmetic and must not stop the app starting.
pub fn viewport_icon() -> Option<egui::IconData> {
    match eframe::icon_data::from_png_bytes(ICON_PNG) {
        Ok(icon) => Some(icon),
        Err(error) => {
            eprintln!("rworldradio: could not decode the embedded icon: {error}");
            None
        }
    }
}

/// Applies the icon to a viewport, leaving it unchanged if decoding failed.
pub fn apply(viewport: egui::ViewportBuilder) -> egui::ViewportBuilder {
    match viewport_icon() {
        Some(icon) => viewport.with_icon(icon),
        None => viewport,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_icon_decodes_to_the_expected_size() {
        let icon = viewport_icon().expect("embedded icon must decode");
        assert_eq!(icon.width, 256);
        assert_eq!(icon.height, 256);
        assert_eq!(icon.rgba.len(), 256 * 256 * 4);
        // Fully transparent everywhere would mean the drawing silently produced
        // nothing.
        assert!(
            icon.rgba.chunks(4).any(|pixel| pixel[3] > 0),
            "icon is entirely transparent"
        );
    }
}
